---
# - name: "install nodejs"
#   apt:
#     name:
#       - nodejs
#       - npm

# - name: install pm2
#   shell: |
#     npm install pm2 -g


- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "Install Node.js 13"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    # Use n version manager to use Node.js v13.8.0
    sudo npm install --global n
    sudo n 13.8.0


- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present